layout_spectrum: 1
name: Ricardo Ceppo
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6340426
  lightness: 0.8085107
  saturation: 0.887234
  rhythmicContrast: 0.4981277
  brandColors:
    - '#000000'
    - '#E7E1D9'
    - '#96928D'
    - '#3F3F3F'
    - '#ECB38D'
typography_spectrum: 0.8085107
